homemine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'))
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register', views.registerUser, name='register_user'),
    path('login_user', views.loginUser, name='login_user'),

    # URLS usuarios logeads
    path('', views.initialPageUser, name='initial_user' ),

    # Rutas de las publicaciones
    path("create_post", views.createNewPost, name='create_post'),

    # Rutas de metadata de publicaciones ( Etiquetas, categorias, albumes)
    path("create_tag", views.createNewTag, name="create_tag")

]

user/models.py
from django.db import models

# Create your models here.

class User(models.Model):
  user_name = models.CharField(max_length=230)
  user_email = models.CharField(max_length=230, unique=True)
  user_password = models.TextField()
  user_rol = models.CharField(max_length=230)

class Posts(models.Model):
  post_date = models.DateField("Creacion de post")
  post_user = models.IntegerField()
  post_title = models.CharField(max_length=245)
  post_desc = models.TextField('Descripcion de post')
  post_image = models.TextField()

class DataPosts(models.Model):
  data_post_title = models.CharField(max_length=245)
  data_post_type = models.CharField(max_length=245)
  data_post_date = models.DateTimeField()
  data_post_user = models.IntegerField(null=True)

user/views.py
from django.shortcuts import render, reverse, redirect
from django.http import JsonResponse
from .models import User, DataPosts, Posts
from django.utils import timezone

# Create your views here.

 
def registerUser(request):
    if request.method == 'POST':
        if request.POST["user_register_name"] == '':
            return False
        if request.POST["user_register_email"] == '':
            return False
        if request.POST["user_register_password"] == '':
            return False
        if request.POST["user_register_rpassword"] == '':
            return False

        if (request.POST["user_register_password"] != request.POST["user_register_rpassword"]):
            return False

        newUserObject = {
            "user_name": request.POST["user_register_name"],
            "user_email": request.POST["user_register_email"],
            "user_password": request.POST["user_register_password"],
            "user_rol": "normal_client"
        }
        existsEmail = User.objects.filter(
            user_email=newUserObject['user_email']).exists()
        if (existsEmail):
            return redirect(reverse("user:register_user") + "?message_register=email_exists")
        else:
            newUser = User(**newUserObject)
            newUser.save()
            return redirect(reverse("user:register_user") + "?message_register=saved")

    else:
        context = dict()
        if request.GET.get("message_register"):
            context["message"] = request.GET["message_register"]
        if request.GET.get("fl"):
            context["fl"] = request.GET["fl"]
        if 'session_id' in request.session:
            context['session_data'] = request.session

        return render(request, 'register_user.html', context)


def loginUser(request):
    userEmail = request.POST["user_login_email"]
    try:
        user = User.objects.get(user_email=userEmail)
        password_passed = request.POST['user_login_password']
        if (user.user_password == password_passed):
            request.session['session_id'] = user.id
            request.session['session_name'] = user.user_name
            request.session['session_email'] = user.user_email
            request.session['session_rol'] = user.user_rol
            return redirect(reverse("user:initial_user"))
        else:
            return redirect(reverse("user:register_user") + "?message_register=email_not_found&fl=1")
    except User.DoesNotExist:
        return redirect(reverse("user:register_user") + "?message_register=email_not_found&fl=1")


####### USUARIOS REGISTRADOS ###############
####### Estas son las rutas de los usuarios registrados. ###########

def initialPageUser(request):

    if not 'session_id' in request.session:
        return redirect(reverse("user:register_user"))
    context = {
        "session": request.session
    }
    return render(request, "loged_users/initial_page.html", context)

## Rutas de publicaciones ##
def createNewPost(request):
    if not 'session_id' in request.session:
        return redirect(reverse("user:register_user"))

    if request.method == "POST":
        context = {
            "images": request.FILES,
            "data": request.POST
        } 
        return render(request, "loged_users/create_post.html", context )
    else:
        theTags = DataPosts.objects.filter(data_post_user=request.session["session_id"])
        context = {
            "session": request.session,
            "tags": theTags
        }
        return render(request, "loged_users/create_post.html", context)

## Rutas de metadata de publcaciones ##

def createNewTag(request):
    if not 'session_id' in request.session:
        return redirect(reverse("user:register_user"))
    
    dataPostContext = {
        "data_post_type": 'tag',
        "data_post_title": request.GET.get('new_title_tag', ""),
        "data_post_date": timezone.now(),
        "data_post_user": request.session["session_id"]
    }
    newDataPost = DataPosts(**dataPostContext)
    newDataPost.save()
    returnData = {
        "success": True,
        "new_data": dataPostContext
    }
    return JsonResponse(returnData)

user/templates/general/footer.html
{% load static %}
  <footer>

    <script src="{% static 'js/custom.js' %}"></script>
  </footer>
</body>

</html>

user/templates/general/header.html
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Titulo de Documento</title>
  {% load static %}
  <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/custom.min.css' %}">
</head>

<body class='{{ body_class|default:"" }}'>
  {% if not hide_header %}
  <header>
    <div class="header_container">
      <div class="header_wrapper">
        <div class="header_left_side">
          <div class="header_logo">
            <div class="logo_min">
              <img src="{% static 'images/homemine_mlogo.png' %}" alt="">
            </div>
          </div>
        </div>
        <div class="header_right_side">
          <nav class='header_nav'>
            <ul>
              <li><a href="">Inicio</a></li>
              <li><a href="">Perfil</a></li>
              <li><a class="close_session" href="">Cerrar Sesion</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
  {% endif %}

user/templates/loged_users/create_post.html
{% include 'general/header.html' with body_class='bg_gray' %}

<section id="create_post" class="section">
  <div class="container">
    <div class="create_post_container">
      <div class="create_post_wrap">
        <div class="hm_box_wrap set_info">
          <div class="hm_box_context">
            <h3 class='text_color'>Comparte tu post</h3>
            <p class="text_color">Añade magia a tu hogar agregando tus experiencias y desiciones para mostrar a el mundo
              quien eres realmente.</p>
            <form action="{% url 'user:create_post' %}" method="post" enctype="multipart/form-data" id="create_post_form">
              {% csrf_token %}
              {% if images %}
                <pre>Images:{{images}}</pre>
              {% endif %}
               {% if data %}
                <pre>Data:{{data}}</pre>
              {% endif %}
              <div class="row">
                <div class="col-md-4">
                  <div class="create_post_image_wrap">
                    <div class="create_post_image_container">
                      <input type="file" id="create_post_image" name='create_post_image' class='input_file'>
                      <i class="icon-camera"></i>
                    </div>
                  </div>
                </div>
                <div class="col-md-8">
                  <div class="field_form">
                    <input placeholder="Titulo de post" id="create_post_title" name="create_post_title" type="text"
                      class='input_text'>
                  </div>
                  <div class="field_form">
                    <textarea class='input_text' placeholder="Descripcion" name="create_post_desc"
                      id="create_post_desc"></textarea>
                  </div>
                  <div class="field_form small field_multiple field_space_between">

                   
                    <select class='select' {% if not tags %} disabled {% endif %}  name='create_post_tag' id="create_post_tag">
                      {% if tags %}
                      {% for tag in tags %}
                        <option value="{{tag.id}}">{{ tag.data_post_title }}</option>
                      {% endfor %}
                      {% endif %}

                      {% if not tags %}
                      <option id="option_no_tags" value="">No existen etiquetas</option>
                      {% endif %}
                    </select>
                    <button type="button" id="toggle_modal_tag" class="button button_small button_green">
                      <i class="icon-plus"></i>
                      <i class="icon-tag"></i>
                    </button>
                  </div>
                  <div class="field_form">
                    <button class="button general_button">
                      Crear
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<div class="modal" id="modal_add_tag">
  <div class="modal_wrap">
    <div class="modal_container">
      <div class="modal_title">
        <h4 class="text_color">Agregar etiqueta</h4>
      </div>
      <div class="modal_body">
        <div class="field_form">
          <label for="">Nombre de etiqueta</label>
          <input type="hidden" value="{{csrf_token}}" id="csrf_token_new_tag">
          {% csrf_token %}
          <input type="text" class="input_text" id="new_title_tag">
        </div>
        <div class="field_form">
          <button class="button general_button" id="action_new_tag">
            Guardar
          </button>
        </div>
      </div>

    </div>
  </div>
</div>

{% include 'general/footer.html' %}

user/templates/loged_users/initial_page.html
{% include 'general/header.html' with body_class='bg_gray' %}

<section id="initial_page" class="section">
  <div class="container">
    <div class="hm_box_wrap inform">
      <div class="hm_box_context">
        <h4 class="text_color">Hola {{ session.session_name}}</h4>
        <p class="text_color mb-25">No tienes posts aun, quieres crear tu primer post?</p>
        <a href="{% url 'user:create_post' %}" class="button general_button button_">Ir alla</a>
      </div>
    </div>
  </div>
</section>

{% include 'general/footer.html' %}

user/templates/register_user.html
{% include 'general/header.html' with hide_header=True %}

{% load static %}
<section id="user_register" class='section h-100vh'>
	<div class="container h-100 d-flex align-items-center">
		<div class="user_register_container">
			{% if nombre %} <p>{{ nombre }}</p> {% endif %}
			<div class="row no-gutters h-100">
				<div class="col-md-6">
					<div class="user_register_bg">
						<div class="logo logo_white user_register_logo">
							<img src="{% static 'images/homemine_logo_white.png' %}" alt="">
						</div>
					</div>
				</div>
				<div class="col-md-6 register_col_wrap {% if fl %}moved{% endif %} ">

					<div class="user_register_form">
						{% if message %}
						{% if message == 'saved' %}
						<div class="user_register_message message message_success">
							<p>Se creado el usuario correctamente</p>

						</div>
						{% elif message == 'email_exists' %}
						<div class="user_register_message message message_error">
							<p>El email ingresado ya existe. Intente con un email distinto.</p>
						</div>
						{% endif %}
						{% endif %}
						<h3 class='user_register_title'>Registrate</h3>

						<p class="text_color">Comparte tus experiencias, en ellas, las personas que mas amas!</p>
						<form action="{% url 'user:register_user' %}" method="post">
							{% csrf_token %}

							<div class="field_form">
								<input class='input_text' type="text" placeholder="Nombre" name="user_register_name"
									id='user_register_name'>
							</div>
							<div class="field_form">
								<input class='input_text' type="text" placeholder="Email" name="user_register_email"
									id='user_register_email' name='user_register_email'>
							</div>
							<div class="field_form">
								<input placeholder="Contraseña" class='input_text' type="password" name="user_register_password"
									id='user_register_password' name='user_register_password'>
							</div>
							<div class="field_form">
								<input placeholder="Repita contraseña" class='input_text' type="password" name="user_register_rpassword"
									id='user_register_rpassword' name='user_register_rpassword'>
							</div>
							<div class="field_form field_multiple field_space_between">
								<div class="register_user_forpass">
									<a href="">¿Olvidó su contraseña?</a>
								</div>
								<input class='button general_button right_button' type="submit" value="Registrar">
							</div>
							<div class="field_form">
								<div class="toggle_access">
									<a class="sublink_box" href="">
										<i class="icon-login"></i>
										<span>¿Ya tienes cuenta?</span>
									</a>
								</div>
							</div>
						</form>
					</div>

					<div class="user_login_form">

						<h3 class='user_register_title'>Ingresa</h3>

						<form action="{% url 'user:login_user'  %}" method="post">
							{% csrf_token %}
							<div class="field_form">
								<input class='input_text' type="text" placeholder="Email" id='user_login_email' name='user_login_email'>
							</div>
							<div class="field_form">
								<input placeholder="Contraseña" class='input_text' type="password" name="user_login_password"
									id='user_login_password'>
							</div>

							<div class="field_form field_multiple field_space_between">
								<div class="register_user_forpass">
									<a href="#">¿Olvidó su contraseña?</a>
								</div>
								<input class='button general_button right_button' type="submit" value="Ingresar">
							</div>
							<div class="field_form">
								<div class="toggle_access">
									<a class="sublink_box" href="#">
										<i class="icon-login"></i>
										<span>¿No tienes cuenta?</span>
									</a>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

	</div>
</section>

{% include 'general/footer.html' %}